# Generated by Django 3.2.5 on 2021-07-27 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_articlemodel_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
